### PR TITLE
Update docfx.json

### PR DESCRIPTION
**Pull request by v-pomanv**

### CODE REVIEW

**Comment by jmazzotta** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Exchange-Articles-2013/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/Exchange-Articles-2013/docfx.json) | :white_check_mark:Succeeded | |
[Exchange-Deployments-2013/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/Exchange-Deployments-2013/docfx.json) | :white_check_mark:Succeeded | |
[exchange-2013-health-management-pack/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/exchange-2013-health-management-pack/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C19%5C1055e55d-3986-8a59-580f-4dcafdff3051%5CPullRequest%5C201806190639370680-4%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GHoTHYQXLX61AZD9vCctKcN%2FyY2PbasdI%2BgEnuv%2BoLs%3D&st=2018-06-19T06%3A37%3A45Z&se=2018-07-20T06%3A42%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Exchange-Articles-2013/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/Exchange-Articles-2013/docfx.json) | :white_check_mark:Succeeded | |
[Exchange-Deployments-2013/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/Exchange-Deployments-2013/docfx.json) | :white_check_mark:Succeeded | |
[Exchange-Server-2013/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/Exchange-Server-2013/docfx.json) | :white_check_mark:Succeeded | |
[exchange-2013-health-management-pack/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/exchange-2013-health-management-pack/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C19%5C1055e55d-3986-8a59-580f-4dcafdff3051%5CPullRequest%5C201806190642424093-4%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3gq9FY7rpDZ8dEhe%2FyZhrjeK9Uo01NhqVoB%2F%2FPfCyy8%3D&st=2018-06-19T06%3A41%3A31Z&se=2018-07-20T06%3A46%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange-2013-health-management-pack/breadcrumb/toc.yml](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/exchange-2013-health-management-pack/breadcrumb/toc.yml) | :warning:Warning | | [Details](#user-content-exchange-2013-health-management-pack%2Fbreadcrumb%2Ftoc.yml)
[Exchange-Articles-2013/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/Exchange-Articles-2013/docfx.json) | :white_check_mark:Succeeded | |
[Exchange-Deployments-2013/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/Exchange-Deployments-2013/docfx.json) | :white_check_mark:Succeeded | |
[Exchange-Server-2013/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/Exchange-Server-2013/docfx.json) | :white_check_mark:Succeeded | |
[exchange-2013-guide-management-pack/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/exchange-2013-guide-management-pack/docfx.json) | :white_check_mark:Succeeded | |
[exchange-2013-health-management-pack/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/exchange-2013-health-management-pack/docfx.json) | :white_check_mark:Succeeded | |

<a name="exchange-2013-health-management-pack%2Fbreadcrumb%2Ftoc.yml"></a>
### [exchange-2013-health-management-pack/breadcrumb/toc.yml](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/exchange-2013-health-management-pack/breadcrumb/toc.yml)
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-msexchangecertificatedeployment-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-messagetracing-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-network-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ecp-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-pop-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-um-callrouter-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-eventassistants-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-outlook-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ecp-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-owa-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-oab-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-imap-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-pop-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-owa-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-compliance-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-transport-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-um-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-powershelldataprovider-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-pushnotifications-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-mailflow-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-store-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-mailboxtransport-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ffowebservice-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-rps-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-activesync-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-antimalware-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-eds-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-oab-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-mrs-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-mailboxmigration-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-userthrottling-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-activesync-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ews-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-autodiscover-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-smtp-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-classification-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ffotransport-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-owa-protocol-dep-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-outlook-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-imap-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-frontendtransport-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-dataprotection-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-um-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-owa-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-mailboxspace-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-autodiscover-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ffoquarantine-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-pop-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-publicfolders-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/exchange-2013-management-pack-health-sets.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-rps-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ews-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-remotemonitoring-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-search-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-outlook-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ad-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ews-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-hubtransport-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ffoumc-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-diskspace-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-clientaccess-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-antispam-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-autodiscover-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-memory-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-activesync-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-imap-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-monitoring-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-freebusy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-sitemailbox-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-fips-health-set.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C19%5C1055e55d-3986-8a59-580f-4dcafdff3051%5CPullRequest%5C201806190645019313-4%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Iwgct66AkZQ6lK6QKqXhC3fbL0XIlZbIHduYAQANF10%3D&st=2018-06-19T06%3A45%3A33Z&se=2018-07-20T06%3A50%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange-2013-health-management-pack/breadcrumb/toc.yml](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/exchange-2013-health-management-pack/breadcrumb/toc.yml) | :warning:Warning | | [Details](#user-content-exchange-2013-health-management-pack%2Fbreadcrumb%2Ftoc.yml)
[Exchange-Articles-2013/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/Exchange-Articles-2013/docfx.json) | :white_check_mark:Succeeded | |
[Exchange-Deployments-2013/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/Exchange-Deployments-2013/docfx.json) | :white_check_mark:Succeeded | |
[Exchange-Server-2013/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/Exchange-Server-2013/docfx.json) | :white_check_mark:Succeeded | |
[exchange-2013-guide-management-pack/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/exchange-2013-guide-management-pack/docfx.json) | :white_check_mark:Succeeded | |
[exchange-2013-health-management-pack/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/exchange-2013-health-management-pack/docfx.json) | :white_check_mark:Succeeded | |

<a name="exchange-2013-health-management-pack%2Fbreadcrumb%2Ftoc.yml"></a>
### [exchange-2013-health-management-pack/breadcrumb/toc.yml](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/exchange-2013-health-management-pack/breadcrumb/toc.yml)
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-msexchangecertificatedeployment-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-messagetracing-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-network-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ecp-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-pop-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-um-callrouter-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-eventassistants-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-outlook-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ecp-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-owa-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-oab-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-imap-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-pop-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-owa-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-compliance-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-transport-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-um-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-powershelldataprovider-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-pushnotifications-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-mailflow-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-store-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-mailboxtransport-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ffowebservice-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-rps-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-activesync-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-antimalware-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-eds-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-oab-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-mrs-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-mailboxmigration-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-userthrottling-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-activesync-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ews-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-autodiscover-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-smtp-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-classification-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ffotransport-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-owa-protocol-dep-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-outlook-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-imap-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-frontendtransport-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-dataprotection-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-um-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-owa-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-mailboxspace-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-autodiscover-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ffoquarantine-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-pop-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-publicfolders-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/exchange-2013-management-pack-health-sets.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-rps-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ews-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-remotemonitoring-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-search-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-outlook-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ad-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ews-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-hubtransport-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ffoumc-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-diskspace-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-clientaccess-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-antispam-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-autodiscover-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-memory-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-activesync-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-imap-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-monitoring-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-freebusy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-sitemailbox-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-fips-health-set.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C19%5C1055e55d-3986-8a59-580f-4dcafdff3051%5CPullRequest%5C201806190939071309-4%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zGgqc%2Bo4TgFlEwkB%2FXjB8IEwFR9RLKAII%2B5F%2FyQdI8c%3D&st=2018-06-19T09%3A37%3A33Z&se=2018-07-20T09%3A42%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange-2013-health-management-pack/breadcrumb/toc.yml](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/exchange-2013-health-management-pack/breadcrumb/toc.yml) | :warning:Warning | | [Details](#user-content-exchange-2013-health-management-pack%2Fbreadcrumb%2Ftoc.yml)
[Exchange-Articles-2013/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/Exchange-Articles-2013/docfx.json) | :white_check_mark:Succeeded | |
[Exchange-Deployments-2013/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/Exchange-Deployments-2013/docfx.json) | :white_check_mark:Succeeded | |
[Exchange-Server-2013/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/Exchange-Server-2013/docfx.json) | :white_check_mark:Succeeded | |
[exchange-2013-guide-management-pack/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/exchange-2013-guide-management-pack/docfx.json) | :white_check_mark:Succeeded | |
[exchange-2013-health-management-pack/docfx.json](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/exchange-2013-health-management-pack/docfx.json) | :white_check_mark:Succeeded | |

<a name="exchange-2013-health-management-pack%2Fbreadcrumb%2Ftoc.yml"></a>
### [exchange-2013-health-management-pack/breadcrumb/toc.yml](https://github.com/v-pomanv/OfficeDocs-Exchange-Test-pr/blob/master/exchange-2013-health-management-pack/breadcrumb/toc.yml)
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-msexchangecertificatedeployment-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-messagetracing-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-network-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ecp-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-pop-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-um-callrouter-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-eventassistants-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-outlook-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ecp-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-owa-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-oab-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-imap-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-pop-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-owa-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-compliance-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-transport-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-um-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-powershelldataprovider-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-pushnotifications-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-mailflow-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-store-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-mailboxtransport-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ffowebservice-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-rps-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-activesync-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-antimalware-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-eds-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-oab-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-mrs-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-mailboxmigration-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-userthrottling-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-activesync-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ews-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-autodiscover-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-smtp-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-classification-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ffotransport-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-owa-protocol-dep-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-outlook-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-imap-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-frontendtransport-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-dataprotection-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-um-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-owa-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-mailboxspace-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-autodiscover-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ffoquarantine-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-pop-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-publicfolders-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/exchange-2013-management-pack-health-sets.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-rps-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ews-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-remotemonitoring-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-search-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-outlook-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ad-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ews-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-hubtransport-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-ffoumc-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-diskspace-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-clientaccess-proxy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-antispam-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-autodiscover-protocol-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-memory-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-activesync-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-imap-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-monitoring-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-freebusy-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-sitemailbox-health-set.md).
 - **[Warning]** Invalid file link:(~/breadcrumb/troubleshooting-fips-health-set.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C19%5C1055e55d-3986-8a59-580f-4dcafdff3051%5CPullRequest%5C201806190940243650-4%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wm%2FPItvSYut48OtJPC4Yj9pB24kkgbyoh%2BV8WbPAtyk%3D&st=2018-06-19T09%3A41%3A26Z&se=2018-07-20T09%3A46%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
Already updated on master

**Pull request closed without merging**
