### PR TITLE
Update docfx.json

### PR DESCRIPTION
**Pull request by v-rajagt**

### CODE REVIEW

**Comment by jmazzotta** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange-2013-health-management-pack/docfx.json](https://github.com/v-rajagt/OfficeDocs-Exchange-Test-pr/blob/bug-fixes/exchange-2013-health-management-pack/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C7%5C1055e55d-3986-8a59-580f-4dcafdff3051%5CPullRequest%5C201806072051104261-1%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QXJGqoGg6agJ84K6sg%2BXQIVH94%2BaIxfapcL5kQ76UWQ%3D&st=2018-06-07T20%3A48%3A03Z&se=2018-07-08T20%3A53%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange-2013-health-management-pack/docfx.json](https://github.com/v-rajagt/OfficeDocs-Exchange-Test-pr/blob/bug-fixes/exchange-2013-health-management-pack/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C7%5C1055e55d-3986-8a59-580f-4dcafdff3051%5CPullRequest%5C201806072207060560-1%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=k2voIc1csordenT6gLE5qh5pPCrDJ4Tt6sBmZbMBCWg%3D&st=2018-06-07T22%3A03%3A19Z&se=2018-07-08T22%3A08%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange-2013-health-management-pack/docfx.json](https://github.com/v-rajagt/OfficeDocs-Exchange-Test-pr/blob/bug-fixes/exchange-2013-health-management-pack/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C7%5C1055e55d-3986-8a59-580f-4dcafdff3051%5CPullRequest%5C201806072216048000-1%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=X3mCCgpLtK2q24MCB4X51RXVxWeIVTsziNsmGdKc9DU%3D&st=2018-06-07T22%3A12%3A16Z&se=2018-07-08T22%3A17%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange-2013-health-management-pack/docfx.json](https://github.com/v-rajagt/OfficeDocs-Exchange-Test-pr/blob/bug-fixes/exchange-2013-health-management-pack/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C7%5C1055e55d-3986-8a59-580f-4dcafdff3051%5CPullRequest%5C201806072253314512-1%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=KXrWWbDLII7nxgcXjb%2BaGPzRjmvNEiV%2BtAjWvFe6y1s%3D&st=2018-06-07T22%3A49%3A48Z&se=2018-07-08T22%3A54%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
changes are obsolete so closing PR without merging.

**Pull request closed without merging**
