### PR TITLE
Task : 1306152 - Analyzed report issue fixed.

### PR DESCRIPTION
**Pull request by v-vijanu**

### CODE REVIEW

**Comment by jmazzotta** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Exchange-Server-2013/configuring-push-notifications-proxying-for-owa-for-devices-exchange-2013-help.md](https://github.com/v-vijanu/OfficeDocs-Exchange-Test-pr/blob/US-1128025_Bug_fixing/Exchange-Server-2013/configuring-push-notifications-proxying-for-owa-for-devices-exchange-2013-help.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/exchange-server-2013/configuring-push-notifications-proxying-for-owa-for-devices-exchange-2013-help?branch=pr-en-us-18) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C20%5C1055e55d-3986-8a59-580f-4dcafdff3051%5CPullRequest%5C201807200023529480-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=HX0%2FCeKBt7Cej9rI1O%2F69tTm8ucSwEdu70A4FXhNMv8%3D&st=2018-07-20T00%3A21%3A32Z&se=2018-08-20T00%3A26%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/OfficeDocs-Exchange-Test-pr, working directory: W:\fg4a-s, target branch: master, target branch commit: 501cf9860f668b8a36ab20589700a92f9d955d00, source branch: 712dd54fa9ce69140623a138dfb56cb7/US-1128025_Bug_fixing, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C20%5C1055e55d-3986-8a59-580f-4dcafdff3051%5CPullRequest%5C201807201543532018-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=A2Xn%2Be7EjVmovYyF11TGo6aAK%2FH%2FkWNdask8H2VcYAI%3D&st=2018-07-20T15%3A39%3A06Z&se=2018-08-20T15%3A44%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Exchange-Server-2013/configuring-push-notifications-proxying-for-owa-for-devices-exchange-2013-help.md](https://github.com/v-vijanu/OfficeDocs-Exchange-Test-pr/blob/US-1128025_Bug_fixing/Exchange-Server-2013/configuring-push-notifications-proxying-for-owa-for-devices-exchange-2013-help.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/exchange-server-2013/configuring-push-notifications-proxying-for-owa-for-devices-exchange-2013-help?branch=pr-en-us-18) |
[Exchange-Server-2013/message-size-limits-exchange-2013-help.md](https://github.com/v-vijanu/OfficeDocs-Exchange-Test-pr/blob/US-1128025_Bug_fixing/Exchange-Server-2013/message-size-limits-exchange-2013-help.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/exchange-server-2013/message-size-limits-exchange-2013-help?branch=pr-en-us-18) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C20%5C1055e55d-3986-8a59-580f-4dcafdff3051%5CPullRequest%5C201807201607494512-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MEORmuA8V8%2Fw0pz%2FBy7UZ7oc7Q90nUKDVgv24vXxDN8%3D&st=2018-07-20T16%3A05%3A46Z&se=2018-08-20T16%3A10%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by DanMSFT** [comment]
Vikram -  I cannot accept the merge yet.  There is markdown inside one of the pages that is appearing in the page.  See below for an example.  Please re-review and fix.  I will leave the PR open in case this speeds up your resolution of this issue.  

image

**Pull request merged**
